import { Urbanist, Alfa_Slab_One } from 'next/font/google'
import Message from '@/components/Message'
import StoreProvider from '@/redux/storeProvider'
import QueryProvider from '@/providers/QueryProvider'
import './globals.css'

export const metadata = {
  title: 'Tejash Creation',
  description: 'Generated by create next app'
}

const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist'
})

const alfaSlabOne = Alfa_Slab_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-alfa'
})

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${urbanist.className} ${alfaSlabOne.variable}`}>
      <body>
        <QueryProvider>
          <StoreProvider>
            {children}
            <Message />
          </StoreProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
