import Message from '@/components/Message'
import './globals.css'
import StoreProvider from '@/redux/storeProvider'

export const metadata = {
  title: 'Tejash Creation',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <StoreProvider>
          {children}
          <Message />
        </StoreProvider>
      </body>
    </html>
  )
}
