import LayoutWrapper from '@/@layouts/LayoutWrapper'
import './globals.css'
import StoreProvider from '@/redux/storeProvider'

export const metadata = {
  title: 'Tejash Creation',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <StoreProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </StoreProvider>
      </body>
    </html>
  )
}
