export const hero = [
  {
    title: "Elevate Your Style with High-Quality Clothing from TejashCreation",
    description:
      "Discover our wide range of clothing options for men, women, and children. Made from 100% pure denim, our garments are both durable and comfortable. Shop with us now and take your wardrobe to the next level.",
    cta: "Shop Now",
  },
  {
    title: "Find Your Perfect Fit at TejashCreation",
    description:
      "From classic cuts to on-trend styles, we have something for everyone. Our clothing is made with attention to detail and a focus on comfort, so you can look and feel your best. Shop with us today and discover your new favorite outfit.",
    cta: "Browse Our Collection",
  },
  {
    title: "Experience the Quality and Style of TejashCreation",
    description:
      "At TejashCreation, we are committed to providing our customers with the best possible shopping experience. From the moment you visit our website, you will be greeted with a wide selection of fashionable and stylish clothing options for all genders. Shop with us now and see the difference for yourself.",
    cta: "Start Shopping",
  },
  {
    title: "Stay Ahead of the Trends with TejashCreation Clothing",
    description:
      "From casual everyday wear to formal occasion dresses, we have the latest styles for every mood and occasion. Our clothing is made with quality materials and attention to detail, ensuring that you always look and feel your best. Shop with us now and stay ahead of the curve.",
    cta: "Shop New Arrivals",
  },
  {
    title: "Get the Best Value for Your Money at TejashCreation",
    description:
      "We believe that high-quality clothing doesn't have to break the bank. That's why we offer a wide range of affordable options for men, women, and children. Shop with us and discover the best value for your money.",
    cta: "View Our Deals",
  },
  {
    title: "Join the TejashCreation Community and Get Exclusive Benefits",
    description:
      "When you shop with us, you're not just getting great clothing - you're joining a community of fashion-forward individuals who love quality and style. As a member of the TejashCreation community, you'll get access to exclusive discounts, early access to new products, and much more. Sign up now and start enjoying the benefits.",
    cta: "Join Now",
  },
  {
    title: "Shop the Best in Quality and Style at TejashCreation",
    description:
      "Our clothing is made with the finest materials and attention to detail, ensuring that you always look and feel your best. From casual wear to formal attire, we have something for every occasion. Shop with us now and experience the difference for yourself.",
    cta: "Shop Now",
  },
  {
    title: "Find Your Perfect Outfit at TejashCreation",
    description:
      "With a wide range of styles and sizes to choose from, we have something for everyone. Our clothing is made with comfort and durability in mind, so you can feel confident and comfortable all day long. Shop with us now and find your perfect outfit.",
    cta: "Browse Our Collection",
  },
  {
    title: "Discover the Best in Fashion at TejashCreation",
    description:
      "From classic cuts to on-trend styles, we have the latest and greatest in fashion. Our clothing is made with quality materials and attention to detail, ensuring that you always look and feel your best. Shop with us now and discover the best in fashion.",
    cta: "Shop Now",
  },
];

export const Categoris = [
  {
    id: 1,
    cat: "footwear",
    img: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Footwear",
  },
  {
    id: 2,
    cat: "clothing",
    img: "https://images.pexels.com/photos/3735641/pexels-photo-3735641.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Clothing",
  },
  {
    id: 3,
    cat: "eyewears",
    img: "https://images.pexels.com/photos/1054777/pexels-photo-1054777.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    title: "EyeWear",
  },
  {
    id: 4,
    cat: "Electronics",
    img: "https://images.pexels.com/photos/583842/pexels-photo-583842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Electronics",
  },
  {
    id: 5,
    cat: "home",
    img: "https://images.pexels.com/photos/1099816/pexels-photo-1099816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Home",
  },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua & Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia & Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central Arfrican Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauro",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre & Miquelon",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "St Kitts & Nevis",
  "St Lucia",
  "St Vincent",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks & Caicos",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

